# Generated by Django 5.0.14 on 2026-07-15 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('population', models.IntegerField()),
                ('taux_urbanisation_pct', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('taux_alphabetisation_pct', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('taux_chomage_pct', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('taux_pauvrete_pct', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('acces_internet_pct', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('centres_sante', models.IntegerField()),
                ('taux_scolarisation_pct', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('production_cerealiere_tonnes', models.FloatField()),
            ],
            options={
                'verbose_name': 'Statistique Régionale',
                'verbose_name_plural': 'Statistiques Régionales',
                'unique_together': {('region', 'annee')},
            },
        ),
    ]
